# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR ORGANIZATION
# Paul lu (digital.xy.hk) 2007.
#
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"POT-Creation-Date: 2007-05-07 22:46+Paris, Madrid\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: Paul lu\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=gb2312\n"
"Content-Transfer-Encoding: ENCODING\n"
"Generated-By: pygettext.py 1.5\n"

### Added recently

#: gpicsync-GUI.py:187
msgid "Quit and save settings"
msgstr ""

##########################

#: gpicsync-GUI.py:131
msgid "Configuration file"
msgstr "设定档"

#: gpicsync-GUI.py:402
msgid "For information, GPX file created with GPSBabel in your picture folder."
msgstr "使用GPSBabel 于相片资料夹内建立了GPX档"

#: gpicsync-GUI.py:404
msgid "Possible problem with the creation of the gpx file"
msgstr "建立GPX档时发生问题"

#: gpicsync-GUI.py:407
msgid "Couldn't create the necessary GPX file."
msgstr "无法建立GPX档" 

#: gpicsync-GUI.py:162
msgid "with TimeStamp"
msgstr "包括时间标记"

msgid "Creating an 'originals-backup' folder."
msgstr "建立 'originals-backup' 资料夹"

msgid "Language"
msgstr "语言"

msgid "languages choice"
msgstr "语言选择"

msgid "Choose a language"
msgstr "选择语言"

msgid "Altitude"
msgstr "高度"

#: ..\..\..\gpicsync-GUI.py:66
msgid "Local time correction"
msgstr "修改本地时间"

#: ..\..\..\gpicsync-GUI.py:67
msgid "&Options"
msgstr "&选项"

#: ..\..\..\gpicsync-GUI.py:69
msgid "About..."
msgstr "关于..."

#: ..\..\..\gpicsync-GUI.py:71
msgid "&Tools"
msgstr "&工具"

#: ..\..\..\gpicsync-GUI.py:72
msgid "EXIF reader"
msgstr "EXIF 阅读器"

#: ..\..\..\gpicsync-GUI.py:73
msgid "Geo-Rename pictures"
msgstr "使用定位资料命名相片"

#: ..\..\..\gpicsync-GUI.py:74 ..\..\..\gpicsync-GUI.py:575
msgid "GPX Inspector"
msgstr "检查GPX档案"

#: ..\..\..\gpicsync-GUI.py:75
msgid "KMZ Generator"
msgstr "制作KMZ档案"

#: ..\..\..\gpicsync-GUI.py:76
msgid "&Help"
msgstr "&说明"

#: ..\..\..\gpicsync-GUI.py:85
msgid "Pictures folder"
msgstr "相片资料夹"

#: ..\..\..\gpicsync-GUI.py:86
msgid "GPS file"
msgstr "GPS档案 "

#: ..\..\..\gpicsync-GUI.py:87
msgid " Synchronise ! "
msgstr " 开始同步！"

#: ..\..\..\gpicsync-GUI.py:88
msgid "Quit"
msgstr "结束"

#: ..\..\..\gpicsync-GUI.py:89
msgid "Stop"
msgstr "停止"

#: ..\..\..\gpicsync-GUI.py:90
msgid "Clear"
msgstr "清除"

#: ..\..\..\gpicsync-GUI.py:91
msgid "View in Google Earth"
msgstr "于Google Earth检视"

#: ..\..\..\gpicsync-GUI.py:93
msgid "UTC Offset="
msgstr "UTC 时差="

#: ..\..\..\gpicsync-GUI.py:94
msgid "Geocode picture only if time difference to nearest track point is below (seconds)="
msgstr "相片定位只会进行当拍摄时间与最接近的定位点相差少于(秒)="

#: ..\..\..\gpicsync-GUI.py:95
msgid "Create a log file in picture folder"
msgstr "于相片资料夹建立记录档"

#: ..\..\..\gpicsync-GUI.py:97
msgid "Dates must match"
msgstr "日期必须吻合"

#: ..\..\..\gpicsync-GUI.py:99
msgid "Create a Google Earth file"
msgstr "建立Google Earth档"

#: ..\..\..\gpicsync-GUI.py:101
msgid "Google Maps export, folder URL="
msgstr "汇出Google Map，资料夹 URL="

#: ..\..\..\gpicsync-GUI.py:103
msgid "backup pictures"
msgstr "备份相片"

#: ..\..\..\gpicsync-GUI.py:105
msgid "interpolation"
msgstr "两点差距运算"

#: ..\..\..\gpicsync-GUI.py:106
msgid "add geonames and geotagged"
msgstr "加入地名及地理资料"

#: ..\..\..\gpicsync-GUI.py:186
msgid "More informations and help:"
msgstr "更多资料及帮助："

#: ..\..\..\gpicsync-GUI.py:203
msgid "To visualize the results in Google Earth you must either:"
msgstr "如须于Google Earth显示结果，您必须："

#: ..\..\..\gpicsync-GUI.py:204 ..\..\..\gpicsync-GUI.py:568
msgid "- finish a synchronisation"
msgstr "- 完成一次同步"

#: ..\..\..\gpicsync-GUI.py:216
msgid "Couldn't find or launch Google Earth"
msgstr "找不到或不能启动Google Earth"

#: ..\..\..\gpicsync-GUI.py:252
msgid "You must first select a pictures folder and a GPX file."
msgstr "您必须首先选择相片资料夹及GPX档案。"

#: ..\..\..\gpicsync-GUI.py:264
msgid "Beginning synchronization with "
msgstr "开始进行同步 "

#: ..\..\..\gpicsync-GUI.py:265
msgid "UTC Offset ="
msgstr "UTC 时差"

#: ..\..\..\gpicsync-GUI.py:266
msgid " hours and maximum time difference = "
msgstr " 小时及最大时间差 = "

#: ..\..\..\gpicsync-GUI.py:274
msgid "Starting to generate a Google Earth file (doc.kml) in the picture folder ..."
msgstr "开始产生Google Earth档案 (doc.kml) 于相片资料夹内 ..."

#: ..\..\..\gpicsync-GUI.py:278
msgid "Starting to generate a Google Map file (doc-web.kml) in the picture folder"
msgstr "开始产生Google Map档案 (doc-web.kml) 于相片资料夹内 ..."

#: ..\..\..\gpicsync-GUI.py:289
msgid "Geocoded with UTC Offset= "
msgstr "已定位，根据UTC时差= "

#: ..\..\..\gpicsync-GUI.py:290
msgid " and  Maximum time difference = "
msgstr " 及最大时间差 = "

#: ..\..\..\gpicsync-GUI.py:292
msgid "Pictures Folder: "
msgstr "相片资料夹："

#: ..\..\..\gpicsync-GUI.py:293
msgid "GPX file: "
msgstr "GPX档案："

#: ..\..\..\gpicsync-GUI.py:307
msgid "(Found "
msgstr "(找到 "

#: ..\..\..\gpicsync-GUI.py:312
msgid "Processed image "
msgstr "已处理相片 "

#: ..\..\..\gpicsync-GUI.py:342
msgid " (writing geonames and geotagged to keywords tag in picture EXIF)"
msgstr " (正在记录地名及地理资料于相片的EXIF关键字标记)"

#: ..\..\..\gpicsync-GUI.py:347
msgid "Couldn't retrieve geonames data..."
msgstr "不能读取地名资料..."

#: ..\..\..\gpicsync-GUI.py:349
msgid "FINISHED GEOCODING PROCESS"
msgstr "完成相片定位"

#: ..\..\..\gpicsync-GUI.py:351
msgid "PROCESSING STOPPED BY THE USER"
msgstr "被使用者终止运作"

#: ..\..\..\gpicsync-GUI.py:355
msgid "Adding the GPS track log to the Google Earth kml file"
msgstr "于Google Earth kml档案加入GPS路径记录"

#: ..\..\..\gpicsync-GUI.py:358
msgid "Click on the 'View in Google Earth' button to visualize the result"
msgstr "点击 '于Google Earth显示' 按钮来显示结果"

#: ..\..\..\gpicsync-GUI.py:359
msgid "( A Google Earth doc.kml file has been created in your picture folder.)"
msgstr "(一个Google Earth doc.kml档案已被建立于相片资料夹内。)"

#: ..\..\..\gpicsync-GUI.py:365
msgid "( A Google Maps doc-web.kml file has been created with the given url )"
msgstr "(一个Google Maps doc-web.kml档案已被建立于设定的url内 )"

#: ..\..\..\gpicsync-GUI.py:380
msgid "Local time corrections"
msgstr "修正本地时间"

#: ..\..\..\gpicsync-GUI.py:383
msgid "Use this option ONLY if your camera local time is wrong."
msgstr "当您的相机时间错误时才使用这个选项。"

#: ..\..\..\gpicsync-GUI.py:384
msgid "Indicate here the local time now displayed by your camera and GPS (hh:mm:ss)"
msgstr "在这里输入相机及GPS现时所显示的时间 (hh:mm:ss)"

#: ..\..\..\gpicsync-GUI.py:386
msgid "Local time displayed now by the camera"
msgstr "相机现时显示的时间"

#: ..\..\..\gpicsync-GUI.py:389
msgid "Local time displayed now by the GPS"
msgstr "GPS现时显示的时间"

#: ..\..\..\gpicsync-GUI.py:392
msgid "Apply correction"
msgstr "确定修正"

#: ..\..\..\gpicsync-GUI.py:406
msgid "EXIF Reader"
msgstr "EXIF读取器"

#: ..\..\..\gpicsync-GUI.py:409
msgid "Read the EXIF metadata of the selected picture."
msgstr "从已选择的相片读取EXIF资料"

#: ..\..\..\gpicsync-GUI.py:411 ..\..\..\gpicsync-GUI.py:412
#: ..\..\..\gpicsync-GUI.py:443
msgid "All EXIF metadata"
msgstr "所有EXIF资料"

#: ..\..\..\gpicsync-GUI.py:413 ..\..\..\gpicsync-GUI.py:446
msgid "Date/Time/Lat./Long."
msgstr "日期/时间/纬度/经度"

#: ..\..\..\gpicsync-GUI.py:419
msgid "Select a picture"
msgstr "选择一张相片"

#: ..\..\..\gpicsync-GUI.py:441
msgid "Selected metada "
msgstr "选择资料 "

#: ..\..\..\gpicsync-GUI.py:451
msgid "lat./long."
msgstr "纬度/经度"

#: ..\..\..\gpicsync-GUI.py:453
msgid "None"
msgstr "无"

#: ..\..\..\gpicsync-GUI.py:459
msgid "Renaming tool"
msgstr "档案命名工具"

#: ..\..\..\gpicsync-GUI.py:462
msgid "This tool renames your pictures with the "
msgstr "这个工具是用来命名您的相片根据"

#: ..\..\..\gpicsync-GUI.py:462
msgid "original time/date and lat./long.(if present)"
msgstr "原来的时间/日期及纬度/经度。(如有)"

#: ..\..\..\gpicsync-GUI.py:464
msgid "Rename pictures in a folder"
msgstr "命名资料夹内所有相片"

#: ..\..\..\gpicsync-GUI.py:465
msgid "Rename a single picture"
msgstr "命名一张相片"

#: ..\..\..\gpicsync-GUI.py:483 ..\..\..\gpicsync-GUI.py:504
msgid "Beginning renaming..."
msgstr "开始命名..."

#: ..\..\..\gpicsync-GUI.py:491 ..\..\..\gpicsync-GUI.py:518
msgid "Didn't find Original Time/Date for "
msgstr "找不到原来的日期/时间于 "

#: ..\..\..\gpicsync-GUI.py:494 ..\..\..\gpicsync-GUI.py:525
msgid "Renamed "
msgstr "已命名"

#: ..\..\..\gpicsync-GUI.py:508
msgid "Interrupted by the user"
msgstr "被使用者终断"

#: ..\..\..\gpicsync-GUI.py:526
msgid "Finished"
msgstr "完成"

#: ..\..\..\gpicsync-GUI.py:533
msgid "Create a kmz file archive"
msgstr "建立kmz档案集"

#: ..\..\..\gpicsync-GUI.py:535
msgid "Create KMZ file !"
msgstr "建立KMZ档案！"

#: ..\..\..\gpicsync-GUI.py:543
msgid "Sorry this tool is not yet available for the Linux version"
msgstr "很抱歉！这个程式暂时未有Linux版本"

#: ..\..\..\gpicsync-GUI.py:552
msgid "Creating a KMZ file in the pictures folder..."
msgstr "建立KMZ档于相片资料夹内..."

#: ..\..\..\gpicsync-GUI.py:555
msgid "Adding doc.kml"
msgstr "正在加入doc.kml"

#: ..\..\..\gpicsync-GUI.py:559
msgid "Adding "
msgstr "正在加入"

#: ..\..\..\gpicsync-GUI.py:563
msgid "KMZ file created in pictures folder"
msgstr "KMZ档已建立于相片资料夹内"

#: ..\..\..\gpicsync-GUI.py:565
msgid "Couldn't rename the zip file to kmz (maybe a previous file already exist)"
msgstr "不能由zip档命名至kmz档 (可能档案已经存在)"

#: ..\..\..\gpicsync-GUI.py:567
msgid "To create a Google Earth kmz file you must either:"
msgstr "如要建立Google Earth kmz档案您必须："

#: ..\..\..\gpicsync-GUI.py:569
msgid "- select a folder you've already synchronized then select the KMZ Generator tool"
msgstr "- 选择一个已同步的资料夹及选择KMZ产生器工具"


#: ..\..\..\gpicsync-GUI.py:578
msgid "Inspect a gpx file and show tracklog data."
msgstr "检查gpx档案及显示轨迹资料。"

#: ..\..\..\gpicsync-GUI.py:580
msgid "Select a gpx file"
msgstr "选择一个gpx档案"

#: ..\..\..\gpicsync-GUI.py:599
msgid "Select a gpx file first."
msgstr "请先选择一个gpx档案。"

#: ..\..\..\gpicsync-GUI.py:602
msgid "Looking at "
msgstr "正检视 "

#: ..\..\..\gpicsync-GUI.py:603
msgid "Number of valid track points found"
msgstr "找到有效的轨迹档数目"

#: ..\..\..\gpicsync-GUI.py:606
msgid "Date"
msgstr "日期"

#: ..\..\..\gpicsync-GUI.py:606
msgid "Time"
msgstr "时间"

#: ..\..\..\gpicsync-GUI.py:607
msgid "Latitude"
msgstr "纬度"

#: ..\..\..\gpicsync-GUI.py:607
msgid "Longitude"
msgstr "经度"

#: ..\..\..\gpicsync.py:186
msgid "taken "
msgstr "已读取 "

#: ..\..\..\gpicsync.py:187 ..\..\..\gpicsync.py:207
msgid "writing best latitude/longitude match to picture: "
msgstr "正在于相片记录最接近的经纬资料："

#: ..\..\..\gpicsync.py:188 ..\..\..\gpicsync.py:194 ..\..\..\gpicsync.py:208
#: ..\..\..\gpicsync.py:215
msgid " time difference (s)= "
msgstr "时间差 (秒)= "

#: ..\..\..\gpicsync.py:193
msgid "no track point below the maximum time range "
msgstr "最大范围内没有定位点 "

#: ..\..\..\gpicsync.py:193 ..\..\..\gpicsync.py:197 ..\..\..\gpicsync.py:215
msgid " : WARNING: DIDN'T GEOCODE, "
msgstr "注意：没有被加入定位资料，"

#: ..\..\..\gpicsync.py:195
msgid " long="
msgstr " 经度="

#: ..\..\..\gpicsync.py:195
msgid "For information nearest trackpoint was at lat="
msgstr "最接近的定位点是位于 纬度="

#: ..\..\..\gpicsync.py:197
msgid "no track point at this picture date "
msgstr "相片日期没有定位点 "

#: ..\..\..\gpicsync.py:210
msgid "Warning: Picture date "
msgstr "请注意：相片日期 "

#: ..\..\..\gpicsync.py:211
msgid " and track point date "
msgstr " 及定位点日期 "

#: ..\..\..\gpicsync.py:211
msgid " are different ! "
msgstr " 是不同的！"

#: ..\..\..\gpicsync.py:215
msgid " no suitable track point below maximum time difference, "
msgstr " 没有同适的定位点于最大的时间差内，"

